out_dir: 'output'
Length: 5000.
Width: 10000.
dx: 50
verbose: 2
N0_meters: 500
Np_water: 2000
Np_sed: 2000
itermax: 2
C0_percent: 0.05
f_bedload: 0.5
h0: 2
u0: 1
coeff_U_dep_mud: 0.5
coeff_U_ero_mud: 1.5
coeff_U_ero_sand: 1.05
save_eta_figs: True
save_eta_grids: True
save_stage_grids: True
save_depth_grids: True
save_discharge_grids: True
save_velocity_grids: True
save_sedflux_grids: True
save_strata: True
save_dt: 172800


matrix:
  SLR:
    - 1e-9
    - 5e-9
    - 1e-8
